AWSTemplateFormatVersion: '2010-09-09'
Description: Batch Instance for aws-hands-on-book

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <控えたAMI IDを入力>
      InstanceType: t3.nano
      SubnetId: <控えたサブネットIDを入力>
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: aws-hands-on-book-batch
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: aws-hands-on-book-batch-sg
      GroupName: aws-hands-on-book-batch-sg
      VpcId: <控えたVPC IDを入力>