AWSTemplateFormatVersion: '2010-09-09'
Description: Batch Instance for aws-hands-on-book 

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <控えたAMI IDを入力>
      InstanceType: t3.nano
      SubnetId: <控えたサブネットIDを入力>
      Tags:
        - Key: Name
          Value: aws-hands-on-book-batch